// Common Indianapolis area street names and neighborhoods
export const indyStreets = [
  "Meridian",
  "College",
  "Delaware",
  "Pennsylvania",
  "Capitol",
  "Illinois",
  "Massachusetts",
  "Virginia",
  "East Washington",
  "West Washington",
  "Market",
  "New York",
  "Michigan",
  "Vermont",
  "North",
  "South",
  "Fall Creek",
  "Broad Ripple",
  "Keystone",
  "Central",
];

export const indyNeighborhoods = [
  "Broad Ripple",
  "Fountain Square",
  "Mass Ave",
  "Irvington",
  "Meridian-Kessler",
  "Downtown",
  "Butler-Tarkington",
  "Castleton",
  "Nora",
  "Glendale",
];
